version: "3"

volumes:
  data:
    driver: local

services:
  lib:
    image: node:18-alpine
    container_name: lib
    restart: unless-stopped
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
