version: "3"

volumes:
  data:
    driver: local

services:
  lib:
    image: node:18-alpine
    container_name: bot
    restart: unless-stopped
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
