version: "3"

volumes:
  data:
    driver: local

services:
  lib:
    build: .
    container_name: bot
    restart: unless-stopped
    working_dir: /app
    command: npm run test:watch
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
